### ISSUE TITLE
Live Data produces errors

### ISSUE THREAD

**Issue by cheak1974** [joqueka/bf4py#17]
Hi,
I tested your library and it is working fine with static data. Unfortunately when I try to retrieve live data with the following code, there are some error message reagarding the requests part of the library (I think).

```
tester = bf4py.BF4Py()

client1 = tester.live_data.price_information(isin='DE000A3CNK42')
client1.open_stream()

client2 = tester.live_data.bid_ask_overview(isin='DE000A3CNK42')
client2.open_stream()

time.sleep(5.0)
```

This code produces the following error message:

```
Exception in thread bf4py.BFStreamClient_bid_ask_overview_DE000A3CNK42:
Traceback (most recent call last):
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\urllib3\util\url.py", line 425, in parse_url
    host, port = _HOST_PORT_RE.match(host_port).groups()  # type: ignore[union-attr]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groups'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\requests\models.py", line 434, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
                                                      ^^^^^^^^^^^^^^
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\urllib3\util\url.py", line 451, in parse_url
    raise LocationParseError(source_url) from e
urllib3.exceptions.LocationParseError: Failed to parse: <Response [200]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "D:\_coding_\test_bf4py\bf4py\live_data.py", line 133, in receive_data
    self.client = self.connector.stream_request(self.endpoint, self.params)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_coding_\test_bf4py\bf4py\connector.py", line 110, in stream_request
    client = sseclient.SSEClient(socket)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\sseclient.py", line 48, in __init__
    self._connect()
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\sseclient.py", line 56, in _connect
    self.resp = requester.get(self.url, stream=True, **self.requests_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\requests\models.py", line 436, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: <Response [200]>
Exception in thread bf4py.BFStreamClient_price_information_DE000A3CNK42:
Traceback (most recent call last):
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\urllib3\util\url.py", line 425, in parse_url
    host, port = _HOST_PORT_RE.match(host_port).groups()  # type: ignore[union-attr]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groups'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\requests\models.py", line 434, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
                                                      ^^^^^^^^^^^^^^
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\urllib3\util\url.py", line 451, in parse_url
    raise LocationParseError(source_url) from e
urllib3.exceptions.LocationParseError: Failed to parse: <Response [200]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "D:\_coding_\test_bf4py\bf4py\live_data.py", line 133, in receive_data
    self.client = self.connector.stream_request(self.endpoint, self.params)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_coding_\test_bf4py\bf4py\connector.py", line 110, in stream_request
    client = sseclient.SSEClient(socket)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\sseclient.py", line 48, in __init__
    self._connect()
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\sseclient.py", line 56, in _connect
    self.resp = requester.get(self.url, stream=True, **self.requests_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\_coding_\test_bf4py\venv\Lib\site-packages\requests\models.py", line 436, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: <Response [200]>
```

I have no clue how to get the live data properly.

Thanks in advance for your help.

regards

Chris

**Comment by SalmIdris** [comment]
Exactly same problem
